### ISSUE TITLE
v0.7.0: Can't remove generated project on Win7

### ISSUE THREAD

**Issue by tohagan** [diegonetto/generator-ionic#161]
Deeply nested dependencies in loadash prevent Windows 7 from removing project generated using the latest 7.0 release.  I've attempted removing the files using Windows explorer and `rm -fr <dir>`.  I'll also post this in the loadash project.   I thought you had removed the dependency on loadash in this release but it may have snuck in via another lower dependency.

![image](https://cloud.githubusercontent.com/assets/301525/6090470/7b8996f4-aec6-11e4-8905-f563d3bb6f20.png)

**Comment by tohagan** [comment]
Solution ... http://superuser.com/questions/755298/how-to-delete-a-file-with-a-path-too-long-to-be-deleted

**Comment by omnibs** [comment]
I always have to rmdir /s node_modules.

The problem is in how inconsistently windows tools handle long paths. Npm team says it's going to change the filesystem layout of modules caches for the next major version.

Some reference:
https://github.com/npm/npm/issues/3697
https://github.com/joyent/node/issues/6960

**Comment by tohagan** [comment]
Thanks for the rmdir tip!  Glad to hear that it's being fixed longer term.
