### ISSUE TITLE
environment specific configuration

### ISSUE THREAD

**Issue by morenoh149** [diegonetto/generator-ionic#40]
vote for adding support for environment configurations. Serious applications usually have development, staging and production environments to roll out new features.
http://newtriks.com/2013/11/29/environment-specific-configuration-in-angularjs-using-grunt/

**Comment by chandramuralis** [comment]
Hi @diegonetto,
   This link https://github.com/diegonetto/generator-ionic#environment-specific-configuration doesn't seems to be active now, could you please point to the latest url?

**Comment by jimthedev** [comment]
https://github.com/diegonetto/generator-ionic/blob/master/docs/FAQ.md#how-do-i-add-constants

**Comment by chandramuralis** [comment]
@jimthedev  thanks. If possible please update this URL in the gruntfile.

**Comment by jimthedev** [comment]
@chandramuralis Would you be willing to make this change via a pull request? It is pretty easy, you can just follow these steps.

1. Go to https://github.com/diegonetto/generator-ionic/blob/master/templates/common/Gruntfile.js

2. Click the little pencil icon at the top of the file to bring you to the propose changes screen.

3. Change line 32 to the correct url: https://github.com/diegonetto/generator-ionic/blob/master/docs/FAQ.md#how-do-i-add-constants

This will fork the repo and put in a pull request so that Diego can accept it.

Thanks!

**Comment by chandramuralis** [comment]
@jimthedev Done and submitted pull request https://github.com/diegonetto/generator-ionic/pull/155
Thanks for the steps, otherwise I would've asked another question.

**Comment by jimthedev** [comment]
@chandramuralis My pleasure. Thanks for being an open source contributor!
