### ISSUE TITLE
Scaffold with ngCordova

### ISSUE THREAD

**Issue by JaKXz** [diegonetto/generator-ionic#58]
I think it would make a great [Y/n] option to include [ngCordova](http://ngcordova.com/), which as you guys probably know by now is made by the good folks at Drifty.

**Comment by pbernasconi** [comment]
In response to what @diegonetto said about the ngCordova file *bloating* an app: When developing an app in Cordova it doesn't really matter what size the file is, because you are not downloading the file from a webserver. Contrary to a web-app, Cordova source files are pre-compiled into the app and thus do not affect the load time of an app.

**Plus**, the minified `ng-cordova.min.js` file is only 82 KB, which is 2X the size of UnderscoreJS -- pretty small if you ask me.

If by *bloated* you mean that there are too many files inside of the Ionic app at the end of the generation, then that is up to you, but I think it would be a good option to allow the developer to decide for himself.

--

I'm not sure you can access the custom build tool in the way that you mentioned, but it might be possible to use the Github API or simple REST calls to the [`/src/plugins`](https://github.com/driftyco/ng-cordova/tree/master/src/plugins) folder and get specific plugins that way. But that sounds like a lot of work to me.

**Comment by jimthedev** [comment]
@pbernasconi I think you have a reasonable point. It'd be interesting to see this implemented. Would you be willing to put in a PR for this? You'd make a lot of people happy. :)

**Comment by pbernasconi** [comment]
Sure thing, I'll get on it tomorrow. @diegonetto would you be willing to accept it?

**Comment by JaKXz** [comment]
Looks like this has been brought in with #152.
